name: "Announce New Release - Discord"
on:
  release:
    types:
      - "published"
jobs:
  announce-new-release-discord:
    name: "Announce New Release - Discord"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction@v4.2.2"
        with:
          key: "${{secrets.DISCORD_HXHS_PROJECTNEWRELEASEANNOUNCER_WEBHOOK}}"
          payload: |
            embeds:
              - title: "GitHub Sodium (NodeJS)"
                description: |
                  > ${{github.event.repository.description}}

                  Version ${{github.event.release.name}} (${{github.event.release.tag_name}}) just released!
                color: "2,110,0"
                thumbnail:
                  url: "https://i.imgur.com/t0myXUU.png"
                fields:
                  - name: "GitHub: ${{github.event.repository.full_name}}"
                    value: "${{github.event.repository.html_url}}"
                    inline: true
                  - name: "GitHub Repository Release & Changelog"
                    value: "${{github.event.release.html_url}}"
                    inline: true
                  - name: "NPM"
                    value: "https://www.npmjs.com/package/@hugoalh/github-sodium"
                    inline: true
                  - name: "．"
                    value: "．"
                    inline: false
                  - name: "Author"
                    value: "${{github.event.release.author.login}}"
                    inline: true
                  - name: "Publish Time"
                    value: "${{github.event.release.published_at}}"
                    inline: true
          wait: "true"
