name: "Announce New Release - Discord"
on:
  release:
    types:
      - "published"
jobs:
  announce-new-release-discord:
    name: "Announce New Release - Discord"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/send-discord-webhook-ghaction@v4.2.1"
        with:
          key: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_PROJECTNEWRELEASEANNOUNCER}}"
          payload: |
            content: |
              **__GitHub Sodium (NodeJS)__**

              Version ${{github.event.release.name}} (${{github.event.release.tag_name}}) is released and available on:

              - **GitHub Repository Release (& Changelog):** <${{github.event.release.html_url}}>
              - **NPM:** <https://www.npmjs.com/package/@hugoalh/github-sodium>
            embeds:
              - description: |
                  **__GitHub Sodium (NodeJS)__**

                  ${{github.event.repository.description}}

                  - **GitHub:** ${{github.event.repository.html_url}}
                color: "2,110,0"
                thumbnail:
                  url: "https://i.imgur.com/iVfV21H.png"
          wait: "true"
