name: "Announce New Release - Discord"
on:
  release:
    types:
      - "published"
jobs:
  announce-new-release-discord:
    name: "Announce New Release - Discord (Reusable Workflow)"
    uses: "hugoalh/hugoalh/.github/workflows/announce-new-release-discord.yml@main"
    with:
      name: "GitHub Sodium (NodeJS)"
      color: "#339933"
      thumbnail: "https://i.imgur.com/t0myXUU.png"
      releases: |
        **- GitHub (& Changelog):** ${{github.event.release.html_url}}
        **- NPM:** https://www.npmjs.com/package/@hugoalh/github-sodium
    secrets:
      DISCORD_WEBHOOK: "${{secrets.DISCORD_HXHS_PROJECTNEWRELEASEANNOUNCER_WEBHOOK}}"
