# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "New Release Announcer - Discord"
on:
  release:
    types:
      - "published"
jobs:
  new-release-announcer-discord:
    name: "New Release Announcer - Discord"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "hugoalh/GitHubAction.SendToDiscord@v3.1.1"
        with:
          configuration: ".github/workflows_configuration/new-release-announcer-discord.yml"
          webhook_id: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_NEWRELEASEANNOUNCER_ID}}"
          webhook_token: "${{secrets.DISCORDWEBHOOK_HUGOALHSTUDIO_STUDIOANNOUNCEMENT_NEWRELEASEANNOUNCER_TOKEN}}"
          variable_join: "."
          # variable_list_external:
          variable_prefix: "%"
          variable_suffix: "%"
