name: "NodeJS Publish"
on:
  release:
    types:
      - "published"
jobs:
  publish-npm:
    name: "Publish To NPM"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v2.1.3"
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org/"
      - name: "Publish To Tag @latest"
        if: ${{github.event.release.prerelease == false}}
        run: "npm publish"
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
      - name: "Publish To Tag @pre"
        if: ${{github.event.release.prerelease == true}}
        run: "npm publish --tag pre"
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
