name: "Publish - NPM"
on:
  release:
    types:
      - "published"
jobs:
  publish-npm:
    name: "Publish - NPM"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.1.0"
      - name: "Modify PowerShell Repository"
        run: |
          Set-PSRepository -Name 'PSGallery' -InstallationPolicy 'Trusted' -Verbose
        shell: "pwsh"
      - name: "Setup GitHub Actions PowerShell Toolkit"
        run: |
          Install-Module -Name 'hugoalh.GitHubActionsToolkit' -MinimumVersion '1.1.1' -Scope 'CurrentUser' -AcceptLicense -Confirm:$False -Verbose
        shell: "pwsh"
      - name: "Get Package Meta"
        id: "get-package-meta"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          [PSCustomObject]$PackageMeta = Get-Content -Path '.\package.json' -Raw -Encoding 'UTF8NoBOM' |
            ConvertFrom-Json -Depth 100
          Set-GitHubActionsOutput -Name 'name' -Value $PackageMeta.name
          Set-GitHubActionsOutput -Name 'version' -Value $PackageMeta.version
        shell: "pwsh"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v3.6.0"
        with:
          node-version: "lts/*"
          check-latest: true
          registry-url: "https://registry.npmjs.org/"
      - name: "Publish To Tag @latest"
        if: "${{github.event.release.prerelease == false || startsWith(steps.get-package-meta.outputs.version, '0.')}}"
        run: |
          npm publish
          npm dist-tag add "${{steps.get-package-meta.outputs.name}}@${{steps.get-package-meta.outputs.version}}" pre
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
      - name: "Publish To Tag @pre"
        if: "${{github.event.release.prerelease == true && !(startsWith(steps.get-package-meta.outputs.version, '0.'))}}"
        run: |
          npm publish --tag pre
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
