name: "Publish - NPM"
on:
  release:
    types:
      - "published"
jobs:
  publish-npm:
    name: "Publish - NPM"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3.0.2"
      - name: "Get Package Meta"
        id: "get-package-meta"
        run: |
          [PSCustomObject]$PackageMeta = Get-Content -Path '.\package.json' -Raw -Encoding 'UTF8NoBOM' |
            ConvertFrom-Json -Depth 100
          Write-Host -Object "::set-output name=name::$($PackageMeta.name)"
          Write-Host -Object "::set-output name=version::$($PackageMeta.version)"
        shell: "pwsh"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v3.5.0"
        with:
          node-version: 14
          check-latest: true
          registry-url: "https://registry.npmjs.org/"
      - name: "Publish To Tag @latest"
        if: "${{github.event.release.prerelease == false || startsWith(steps.get-package-meta.outputs.version, '0.')}}"
        run: |
          npm publish
          npm dist-tag add "${{steps.get-package-meta.outputs.name}}@${{steps.get-package-meta.outputs.version}}" pre
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
      - name: "Publish To Tag @pre"
        if: "${{github.event.release.prerelease == true && !(startsWith(steps.get-package-meta.outputs.version, '0.'))}}"
        run: |
          npm publish --tag pre
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
